import React from "react";
import styles from "../styles/Loader.module.css";

export default function Loader() {
  const crossImages = [];
  for (let i = 0; i < 100; i++) {
    crossImages.push(<img className={styles.cross} src={"cross.png"} />);
  }

  return (
    <div className={styles.mainContainer}>
      <div className={styles.picContainer}>
        <div className={styles.crossContainer}>
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
          <img className={styles.cross} src={"cross.png"} />
        </div>
        <img className={styles.pic} src={"Maroc-47.jpg"} />
      </div>
      <div className={styles.text}>CHARGEMENT</div>
    </div>
  );
}
